project_id = "hmdxufttehhpyyqoaosz"

[auth]
enabled = true
site_url = "https://lovable.dev"

[functions.analyze-cv]
verify_jwt = true

[functions.analyze-rei-profile]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.twitter-oauth]
verify_jwt = false

[functions.submit-rei-registration]
verify_jwt = false

[functions.submit-whitelist-request]
verify_jwt = false

[functions.approve-whitelist-submission]
verify_jwt = true

[functions.send-twitter-dm]
verify_jwt = false